# Generated by Django 4.2.7 on 2023-11-14 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_selledproduct_type_of_price'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deptarrivedcargo',
            name='cargo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.kelganproduct'),
        ),
    ]
