# Generated by Django 4.2.7 on 2023-11-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_deptarrivedcargo_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deptarrivedcargo',
            name='amount',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
