# Generated by Django 4.2.7 on 2023-11-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_debtcustomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='deptarrivedcargo',
            name='payed_amount',
            field=models.BooleanField(default=0),
        ),
    ]
