# Generated by Django 3.2 on 2023-11-01 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='product_images/')),
                ('olingan_price', models.PositiveBigIntegerField(help_text='Mahsulotni olib kelingan narxi')),
                ('sotuv_price', models.PositiveBigIntegerField(help_text='Mahsulotni sotilish narxi')),
                ('optom_price', models.PositiveBigIntegerField(help_text='Mahsulotni optom narxi')),
                ('olchov_usuli', models.CharField(choices=[('kg', 'Kilogram'), ('metr', 'Metr'), ('pc', 'Dona'), ('litr', 'Litr')], max_length=5)),
                ('quantity', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
