# Generated by Django 3.2 on 2023-11-01 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='soni',
        ),
    ]
