# Generated by Django 4.2.7 on 2023-11-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_customer_kelganproduct_user_selledproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='selledproduct',
            name='type_of_price',
            field=models.CharField(choices=[('selling', 'Sotilish Narxi'), ('wholesale', 'Optom Narxi'), ('actual', 'Haqiqiy Narxi')], default=1, max_length=25),
            preserve_default=False,
        ),
    ]
