# Generated by Django 4.2.7 on 2023-11-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_selledproduct_type_of_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='amount',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kelganproduct',
            name='amount',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
